\documentclass[final,9pt,fleqn]{beamer}
\input{BeamOptions.tex}

\setbeamertemplate{footline}{\hfill {\footnotesize \href{https://creativecommons.org/licenses/by-sa/4.0/}{CC BY-SA 4.0} $\circ$ Nicholas J. Clark $\circ$ Learn more at \href{https://nicholasjclark.github.io/mvgam/index.html}{https://nicholasjclark.github.io/mvgam/index.html} $\circ$ package version $1.0.9$ $\circ$ updated: \today} \hspace {0.1in} \vspace{0.1in}}

\begin{document}

<<include=FALSE>>=
library(knitr)
opts_chunk$set(
concordance=TRUE
)
@



<<setup, include=FALSE>>=
library(knitr)
options(replace.assign=TRUE, width=50, digits=4)
opts_knit[["set"]](progress=FALSE)
library("ggplot2"); theme_set(theme_classic(base_family = 'serif'))
library("mvgam")
@

<<include=FALSE, cache=TRUE>>=
set.seed(1234)
simdat <- sim_mvgam(n_series = 1)
model <- mvgam(y ~ s(season, bs = 'cc'),
               trend_model = RW(),
               data = simdat$data_train)
fc <- forecast(model, newdata = simdat$data_test)
@

\begin{frame}[fragile]
  \frametitle{{\fontsize{41}{43} \selectfont \textcolor{mygray}{mvgam ::}} {\fontsize{25}{25} \textbf{\textcolor{mygray}{CHEATSHEET}}}}
\vspace{-0.6in}
  \begin{columns}
    \begin{column}{0.02\paperwidth} % left margin space
    \end{column}

    \begin{column}{0.3\paperwidth}

\begin{block}
\noindent\makebox[\linewidth]{\rule{0.3\paperwidth}{0.2pt}}

The \texttt{mvgam} package provides tools for fitting and interrogating univariate or multivariate State-Space time series models that can include nonlinear smooth functions of covariates, dynamic temporal processes and random effects. A wide variety of latent dynamic processes can be specified. The package also provides tools for interpreting effects, computing and scoring forecasts, as well as generating model code and data objects for further customisation. Models are fitted using \texttt{Stan} for full Bayesian inference.

\end{block}

\begin{block}{{\fontsize{21}{21} \selectfont \color{BrickRed} Modelling with \texttt{\color{Orchid} mvgam()}}}
Usage: \texttt{\color{Orchid} mvgam(formula, trend\_formula, data, trend\_model, family, ...)}

\medskip
\texttt{\color{Orchid} formula}: observation model regression formula, built off the \texttt{mgcv} package. See \texttt{\color{Orchid}?mvgam\_formulae} for more guidance

\medskip
\texttt{\color{Orchid} trend\_formula}: optional process model formula (see \href{https://nicholasjclark.github.io/mvgam/articles/trend_formulas.html}{the State-Space model vignette} and \href{https://nicholasjclark.github.io/mvgam/articles/trend_formulas.html}{the shared latent states vignette} for guidance on using trend formulae)

\medskip
\texttt{\color{Orchid} data}: a \texttt{data.frame} or \texttt{list} containing the response variable(s) and optional predictor variables. See \href{https://nicholasjclark.github.io/mvgam/articles/data_in_mvgam.html}{the data formatting vignette} for guidance on data preparation

\medskip
\texttt{\color{Orchid} trend\_model}: optional latent dynamic process. Options include (among others):
\begin{itemize}

\item\texttt{\color{Orchid} None}: default, no dynamic process

\item\texttt{\color{Orchid} RW(ma = FALSE, cor = FALSE)}: random walk

\item\texttt{\color{Orchid} AR(p = 1, ma = FALSE, cor = FALSE)}: autoregressive

\item\texttt{\color{Orchid} VAR(ma = FALSE, cor = FALSE)}: vector autoregressive

\item\texttt{\color{Orchid} PW(growth = 'linear')}: piecewise linear

\item\texttt{\color{Orchid} PW(growth = 'logistic')}: piecewise logistic, with max saturation

\item\texttt{\color{Orchid} GP()}: squared exponential Gaussian Process
\end{itemize}
For autoregressive processes (\texttt{\color{Orchid} RW(), AR() or VAR()}), moving average and correlated process errors can also be specified by changing the \texttt{\color{Orchid} ma} and \texttt{\color{Orchid} cor} arguments

\medskip
\texttt{\color{Orchid} family}: observation distribution. Options include (among others):
\begin{itemize}

\item\texttt{\color{Orchid} gaussian()}: Gaussian with identity link

\item\texttt{\color{Orchid} student-t()}: Student's T with identity link

\item\texttt{\color{Orchid} lognormal()}: LogNormal with identity link

\item\texttt{\color{Orchid} Gamma()}: Gamma with log link

\item\texttt{\color{Orchid} betar()}: Beta with logit link

\item\texttt{\color{Orchid} poisson()}: Poisson with log link

\item\texttt{\color{Orchid} nb()}: Negative Binomial with log link
\end{itemize}

\medskip
See \href{https://nicholasjclark.github.io/mvgam/articles/mvgam_overview.html}{the introductory vignette} for more guidance on supported families and dynamic processes

\medskip
\texttt{\color{Orchid} ...}: other arguments such as user-specified \texttt{\color{Orchid} priors}, \texttt{\color{Orchid} newdata} for generating probabilistic forecasts and options to control \texttt{\color{Orchid} Stan} MCMC parameters

\medskip
\textbf{\color{BrickRed} Prior to modelling}, it is useful to:
\begin{itemize}

\item Inspect features of the data with \texttt{\color{Orchid} plot\_mvgam\_series()}

\item Ensure there are no \texttt{\color{Orchid} NA}'s in predictors (though \texttt{\color{Orchid} NA}'s are allowed in response variables). See \href{https://nicholasjclark.github.io/mvgam/articles/data_in_mvgam.html}{the data formatting vignette} for guidance on data preparation

\item Inspect default priors with \texttt{\color{Orchid} get\_mvgam\_priors()}

\item Make any necessary changes to default priors with \texttt{\color{Orchid} prior()}

\end{itemize}

\medskip
\texttt{\color{Orchid} sim\_mvgam()} is useful to generate simple example datasets
<<eval=FALSE>>=
simdat <- sim_mvgam(n_series = 1)
model <- mvgam(formula = y ~ s(season, bs = 'cc'),
               trend_model = RW(), data = simdat$data_train)
@

Use \texttt{\color{Orchid} stancode(model)} to see the auto-generated \texttt{Stan} code

\end{block}
\end{column}


\begin{column}{.03\paperwidth}
\end{column}


\begin{column}{0.3\paperwidth}
\vspace{0.52in}
\noindent\makebox[\linewidth]{\rule{0.3\paperwidth}{0.2pt}}
\begin{block}{{\fontsize{21}{21} \selectfont \color{BrickRed} Diagnostics and Inference}}

\smallskip
{{\fontsize{11}{11} \selectfont \color{mygray} What effects has the model estimated?}}

\medskip
\texttt{\color{Orchid} summary(model)} and \texttt{\color{Orchid} coef(model)}: posterior summaries and diagnostics

\medskip
\texttt{\color{Orchid} fitted(model)}, \texttt{\color{Orchid} logLik(model)} and \texttt{\color{Orchid} residuals(model)}: posterior expectations, pointwise Log-Likelihoods and randomized quantile residuals

\medskip
\texttt{\color{Orchid} loo(model)} and \texttt{\color{Orchid} loo\_compare(model1, model2, ...)}: calculate approximate leave-one-out information criteria for model comparisons

\medskip
\texttt{\color{Orchid} mcmc\_plot(model)}: visualize posterior summaries, pairs plots and a wide range of MCMC diagnostics using functionality from the \texttt{Bayesplot} package

<<fig.width=6, fig.height=2, fig.align='center', warning=FALSE, echo=FALSE>>=
mcmc_plot(model, variable = '(Intercept)', type = 'combo')
@

\medskip
Use \texttt{\color{Orchid} as.data.frame(model)}, \texttt{\color{Orchid} as.matrix(model)}, or \texttt{\color{Orchid} as.array(model)} to extract posterior parameter estimates. Use \texttt{\color{Orchid} variables(model)} to determine what parameters are available for extraction

\medskip
The \texttt{S3} \texttt{\color{Orchid} plot()} function applied to models can visualise smooth functions (\texttt{\color{Orchid} type = 'smooths'}), random effects (\texttt{\color{Orchid} type = 're'}), conditional predictions and trend estimates (\texttt{\color{Orchid} type = 'forecast'} or \texttt{\color{Orchid} type = 'trend'}), uncertainty contributions (\texttt{\color{Orchid} type = 'uncertainty'}) or randomized quantile residual diagnostics (\texttt{\color{Orchid} type = 'residuals'}). Use \texttt{\color{Orchid} trend\_effects = TRUE} to visualise effects from any process model formulae

\medskip
\texttt{\color{Orchid} conditional\_effects(model)} gives useful conditional effect plots on either the response or the link scale

\smallskip
<<fig.width=4, fig.height=1.75, fig.align='center', warning=FALSE, echo=FALSE>>=
conditional_effects(model)[[1]] +
  xlim(c(1, 12.1)) +
  theme_classic(base_size = 10,
                base_family = 'serif')
@

For most \texttt{mvgam} models, functions from the \texttt{marginaleffects} package can be used for more targeted prediction-based inference. See \href{https://marginaleffects.com/}{The Marginal Effects Zoo} and \href{https://ecogambler.netlify.app/blog/interpreting-gams/}{How to interpret effects from GAMs} for guidance on inspecting predictions, slopes and comparisons
<<fig.width=4, fig.height=1.75, fig.align='center', warning=FALSE, echo=FALSE>>=
post_contrasts <- marginaleffects::avg_comparisons(model,
                                  variables = list(season = c(5, 11))) %>%
  marginaleffects::posteriordraws()

post_contrasts %>%
  ggplot(aes(x = draw)) +
  tidybayes::stat_halfeye(fill = "#C79999") +
  labs(x = "(season = 11) − (season = 5) posterior contrast", y = "Density") +
  theme_classic(base_size = 10,
                base_family = 'serif')
@

\end{block}
\end{column}


\begin{column}{.03\paperwidth}
\end{column}


\begin{column}{0.3\paperwidth}
\vspace{0.37in}
\noindent\makebox[\linewidth]{\rule{0.3\paperwidth}{0.2pt}}
\begin{block}{{\fontsize{21}{21} \selectfont \color{BrickRed} Prediction and forecasting}}

\smallskip
{{\fontsize{11}{11} \selectfont \color{mygray} How good are model predictions?}}

\medskip
Use \texttt{\color{Orchid} predict(model)} with \texttt{\color{Orchid} newdata} to make predictions for inference purposes. Change the \texttt{\color{Orchid} type} argument for different types of predictions (link scale, expectation or response scale). Or use the \texttt{brms} package equivalents \texttt{\color{Orchid} posterior\_predict(model)}, \texttt{\color{Orchid} posterior\_linpred(model)} or \texttt{\color{Orchid} posterior\_epred(model)}. If generating forecasts for future timepoints, use the \texttt{\color{Orchid} forecast()} function (see below)

\medskip
Use \texttt{\color{Orchid} ppc(model)} and \texttt{\color{Orchid} pp\_check(model)} to compute conditional or unconditional posterior predictive checks and compare model predictions against the true observations

\medskip
Extract in-sample posterior predictions with \texttt{\color{Orchid} hindcast(model)}. If validation data exist, generate forecast predictions with \texttt{\color{Orchid} forecast(model, newdata = newdata)}. As above, change the \texttt{\color{Orchid} type} argument for predictions on different scales. Both functions generate an object of class \texttt{mvgam\_forecast}, that can be plotted with an \texttt{S3} \texttt{\color{Orchid} plot()} function. See \href{https://nicholasjclark.github.io/mvgam/articles/forecast_evaluation.html}{the forecasting vignette} for more details about how to produce forecasts.

<<fig.width=5.4, fig.height=2.5, fig.align='center', warning=FALSE, message=FALSE, results='hide',echo=FALSE>>=
  par(family = "serif",
      las = 1,
      mar=c(3,3,2,2),
      mgp = c(2,0.5,0),
      bty = "l",
      cex.axis = 0.9,
      cex.lab = 0.9,
      cex.main = 0.9,
      xaxs = 'r',
      yaxs = 'r',
      pch = 16)
plot(fc)
@

\smallskip
Compute probabilistic forecast scores using proper scoring rules with the \texttt{\color{Orchid} score()} function:
<<eval=FALSE>>=
fc <- forecast(model, newdata = simdat$data_test, type = 'response')
crps <- score(fc, score = 'crps')
dplyr::glimpse(crps$series_1)
@

<<echo=FALSE>>=
crps <- score(fc, score = 'crps')
dplyr::glimpse(crps$series_1)
@
\smallskip
Available proper scoring rules in the \texttt{\color{Orchid} score()} function include:
\begin{itemize}

\item \texttt{\color{Orchid} type = 'crps'}: Continuous Rank Probability Score (univariate)
\item \texttt{\color{Orchid} type = 'drps'}: Discrete Rank Probability Score (univariate)
\item \texttt{\color{Orchid} type = 'elpd'}: Expected Log Predictive Density (univariate)
\item \texttt{\color{Orchid} type = 'sis'}: Scaled Interval Score (univariate)
\item \texttt{\color{Orchid} type = 'energy'}: Energy Score (multivariate)
\item \texttt{\color{Orchid} type = 'variogram'}: Variogram Score (multivariate)
\end{itemize}

\medskip
Use \texttt{\color{Orchid} lfo\_cv(model)} for approximate leave-future-out cross-validation with an expanding window training technique (see \href{https://www.tandfonline.com/doi/full/10.1080/00949655.2020.1783262}{Bürkner et al. 2020} for details of the algorithm). This generates expected log predictive density scores at user-specified forecast horizons, which can be used to compare different models

\end{block}
\end{column}

\end{columns}
\end{frame}

\end{document}
