// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// trend_arma_recursC
arma::mat trend_arma_recursC(const arma::ivec& ar_lags, const arma::ivec& ma_lags, const arma::vec& drift, const arma::cube& A, const arma::cube& B, const arma::mat& innovations, const arma::mat& linpreds, const arma::mat& last_trends, int h);
RcppExport SEXP _mvgam_trend_arma_recursC(SEXP ar_lagsSEXP, SEXP ma_lagsSEXP, SEXP driftSEXP, SEXP ASEXP, SEXP BSEXP, SEXP innovationsSEXP, SEXP linpredsSEXP, SEXP last_trendsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ivec& >::type ar_lags(ar_lagsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type ma_lags(ma_lagsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type drift(driftSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type innovations(innovationsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type linpreds(linpredsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type last_trends(last_trendsSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(trend_arma_recursC(ar_lags, ma_lags, drift, A, B, innovations, linpreds, last_trends, h));
    return rcpp_result_gen;
END_RCPP
}
// car1_recursC
arma::mat car1_recursC(const arma::vec& phi, const arma::vec& sigma, const arma::vec& time_dis, const arma::mat& innovations, const arma::vec& last_trend, int h);
RcppExport SEXP _mvgam_car1_recursC(SEXP phiSEXP, SEXP sigmaSEXP, SEXP time_disSEXP, SEXP innovationsSEXP, SEXP last_trendSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time_dis(time_disSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type innovations(innovationsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type last_trend(last_trendSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(car1_recursC(phi, sigma, time_dis, innovations, last_trend, h));
    return rcpp_result_gen;
END_RCPP
}
// pw_trendC
arma::mat pw_trendC(const arma::vec& t, const arma::vec& k, const arma::vec& m, const arma::mat& delta, const arma::vec& t_change, const arma::mat& cap, const std::string& growth_type);
RcppExport SEXP _mvgam_pw_trendC(SEXP tSEXP, SEXP kSEXP, SEXP mSEXP, SEXP deltaSEXP, SEXP t_changeSEXP, SEXP capSEXP, SEXP growth_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type t_change(t_changeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cap(capSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type growth_type(growth_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(pw_trendC(t, k, m, delta, t_change, cap, growth_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvgam_trend_arma_recursC", (DL_FUNC) &_mvgam_trend_arma_recursC, 9},
    {"_mvgam_car1_recursC", (DL_FUNC) &_mvgam_car1_recursC, 6},
    {"_mvgam_pw_trendC", (DL_FUNC) &_mvgam_pw_trendC, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvgam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
