// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ar3_recursC
Rcpp::NumericVector ar3_recursC(double drift, double ar1, double ar2, double ar3, Rcpp::NumericVector linpreds, Rcpp::NumericVector errors, Rcpp::NumericVector last_trends, int h);
RcppExport SEXP _mvgam_ar3_recursC(SEXP driftSEXP, SEXP ar1SEXP, SEXP ar2SEXP, SEXP ar3SEXP, SEXP linpredsSEXP, SEXP errorsSEXP, SEXP last_trendsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type drift(driftSEXP);
    Rcpp::traits::input_parameter< double >::type ar1(ar1SEXP);
    Rcpp::traits::input_parameter< double >::type ar2(ar2SEXP);
    Rcpp::traits::input_parameter< double >::type ar3(ar3SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type linpreds(linpredsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type errors(errorsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type last_trends(last_trendsSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(ar3_recursC(drift, ar1, ar2, ar3, linpreds, errors, last_trends, h));
    return rcpp_result_gen;
END_RCPP
}
// var1_recursC
arma::mat var1_recursC(arma::mat A, arma::mat linpreds, arma::mat errors, arma::rowvec drift, arma::rowvec last_trends, int h);
RcppExport SEXP _mvgam_var1_recursC(SEXP ASEXP, SEXP linpredsSEXP, SEXP errorsSEXP, SEXP driftSEXP, SEXP last_trendsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type linpreds(linpredsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type errors(errorsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type drift(driftSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type last_trends(last_trendsSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(var1_recursC(A, linpreds, errors, drift, last_trends, h));
    return rcpp_result_gen;
END_RCPP
}
// varma_recursC
arma::mat varma_recursC(arma::mat A, arma::mat A2, arma::mat A3, arma::mat theta, arma::mat linpreds, arma::mat errors, arma::rowvec drift, arma::mat last_trends, int h);
RcppExport SEXP _mvgam_varma_recursC(SEXP ASEXP, SEXP A2SEXP, SEXP A3SEXP, SEXP thetaSEXP, SEXP linpredsSEXP, SEXP errorsSEXP, SEXP driftSEXP, SEXP last_trendsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A3(A3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type linpreds(linpredsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type errors(errorsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type drift(driftSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type last_trends(last_trendsSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(varma_recursC(A, A2, A3, theta, linpreds, errors, drift, last_trends, h));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mvgam_ar3_recursC", (DL_FUNC) &_mvgam_ar3_recursC, 8},
    {"_mvgam_var1_recursC", (DL_FUNC) &_mvgam_var1_recursC, 6},
    {"_mvgam_varma_recursC", (DL_FUNC) &_mvgam_varma_recursC, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvgam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
