# Implementation of `posterior_smooths.mvgam` and
# `conditional_smooths.mvgam`. The mvgam stancode is generated by
# brms's own machinery, so the parameter blocks for `s(...)`,
# `t2(...)`, `ti(...)`, `te(...)` terms follow brms's positional
# Stan-name conventions exactly:
#   * `Xs` (or `Xs_trend`)            - fixed unpenalised basis
#   * `Zs_<row>_<j>` (`_trend`)       - per-penalty random-effect basis
#   * `bs[k]` (`bs_trend[k]`)         - fixed-effect coefficients
#   * `s_<row>_<j>[k]` (`_trend`)     - random-effect coefficients
#   * `sds_<row>[k]` (`_trend`)       - smoothing standard deviations
# `<row>` indexes the smframe (one row per smooth term, expanded
# per by-level for `s(x, by = factor)`). The fixed-effect block
# also carries an `attr(Xs, "smcols")` list that maps each smframe
# row to its columns in `Xs`. By-factor smooths produce consecutive
# rows, one per level of the by-factor; their `smcols` entries
# together span the focal smooth.
#
# The aliaser in `mvgam_beta_aliases()` renames `bs[k]` to
# `bs_<colname>` (and `bs_trend[k]` to `bs_<colname>_trend`) so we
# can fetch coefficients by their brms-native names rather than by
# raw positional index. Random-effect coefficients stay under
# their positional `s_<row>_<j>[k]` names because brms does too.


#' Compute posterior draws of a smooth term in a fitted
#' \pkg{mvgam} model
#'
#' Returns the posterior draws of a single smooth term evaluated
#' at the supplied prediction grid, matching the shape of
#' [brms::posterior_smooths()]. Supports any smooth declared by
#' `s()`, `t2()`, `ti()`, or `te()` on either the observation
#' formula or the trend formula, including `by = factor`
#' expansion.
#'
#' @param object A fitted `mvgam` object.
#' @param smooth Character string naming the smooth term as it
#'   appears in the formula (e.g. `"s(x)"`,
#'   `"s(z, by = group)"`, `"t2(x, y)"`). Use
#'   [smooths.mvgam()] to enumerate the available terms.
#' @param newdata Optional `data.frame` to evaluate the smooth
#'   at. `NULL` (the default) uses the training data.
#' @param resp,dpar,nlpar Retained for brms-parity. mvgam fits
#'   are currently univariate on a single distributional
#'   parameter; supplying non-`NULL` values raises an error.
#' @param ndraws,draw_ids Optional posterior-draw subsetting,
#'   matching the [brms::posterior_smooths()] semantics.
#' @param ... Unused; present for S3 / brms-parity.
#'
#' @return A numeric matrix of dimension
#'   \[n_draws x n_grid_points\] containing the posterior draws
#'   of the smooth term's contribution to the linear predictor.
#'
#' @details
#' The smooth's contribution is computed as
#' `Xs_focal %*% bs_focal + sum_j Zs_j %*% s_j` per draw, where
#' the basis matrices come from `brms::standata()` evaluated on
#' `newdata`, and the coefficients come from the cached posterior
#' draws (already routed through the mvgam aliaser).
#'
#' For trend-side smooths the same logic applies against the
#' `_trend` parameter block.
#'
#' @seealso [brms::posterior_smooths()],
#'   [conditional_smooths.mvgam()], [smooths.mvgam()].
#'
#' @author Nicholas J Clark
#'
#' @examples
#' \dontrun{
#' set.seed(13)
#' simdat <- sim_mvgam(family = poisson(), n_series = 1L,
#'                      n_timepoints = 120L, trend_model = AR())
#' mod <- mvgam(y ~ s(x), trend_formula = ~ AR(p = 1),
#'               data    = simdat$data_train,
#'               family  = poisson(),
#'               chains  = 2, silent = 2)
#'
#' # Posterior draws of the s(x) smooth at the training x values.
#' sm <- posterior_smooths(mod, smooth = "s(x)")
#' dim(sm)
#' }
#'
#' @method posterior_smooths mvgam
#' @export
posterior_smooths.mvgam <- function(object, smooth, newdata = NULL,
                                     resp = NULL, dpar = NULL, nlpar = NULL,
                                     ndraws = NULL, draw_ids = NULL, ...) {
  checkmate::assert_class(object, "mvgam")
  checkmate::assert_string(smooth)
  if (!is.null(newdata)) {
    checkmate::assert_data_frame(newdata, min.rows = 1L)
  }
  if (!is.null(ndraws)) {
    checkmate::assert_int(ndraws, lower = 1L)
  }
  if (!is.null(draw_ids)) {
    checkmate::assert_integerish(draw_ids, lower = 1L, min.len = 1L)
  }
  if (!is.null(resp) || !is.null(dpar) || !is.null(nlpar)) {
    stop(insight::format_error(c(
      paste0(
        "'resp', 'dpar' and 'nlpar' are accepted for ",
        "brms-parity but are not supported on 'mvgam' fits."
      ),
      i = paste0(
        "'posterior_smooths()' evaluates the smooths of one ",
        "response on a single distributional parameter."
      )
    )))
  }
  hit <- resolve_mvgam_smooth(object, smooth)
  # A count becomes indices at the boundary, so nothing below chooses
  # its own draws.
  mvgam_smooth_eta(
    object, hit, newdata,
    draw_ids = resolve_draw_ids(object, ndraws, draw_ids)
  )
}


#' @importFrom brms posterior_smooths
#' @export
brms::posterior_smooths


#' Marginal smooth-effect plots for a fitted \pkg{mvgam} model
#'
#' Compute and display posterior conditional effects for every
#' smooth term in a fitted `mvgam` object, matching the shape of
#' \code{\link[brms]{conditional_smooths.brmsfit}}. Returns a named list of
#' `data.frame`s with the brms-style `estimate__` / `lower__` /
#' `upper__` / `effect1__` / `effect2__` / `cond__` columns. The
#' returned object carries the `mvgam_conditional_smooths` class;
#' one-dimensional smooths render with the package's own theme via
#' [plot.mvgam_conditional_smooths()], while two-dimensional cases
#' are drawn as heatmap panels through the same method.
#'
#' @param x A fitted `mvgam` object.
#' @param smooths Optional character vector restricting which
#'   smooth terms to compute. `NULL` (default) returns every
#'   smooth on both the observation and trend formulas.
#' @param int_conditions Optional named list. Each name is a
#'   covariate; each value either a numeric vector of conditioning
#'   values or a function applied to the original covariate. Used
#'   for non-focal covariates that appear in by-factor faceting.
#' @param prob Numeric in `(0, 1)`. The credible-interval mass
#'   reported via `lower__` / `upper__`. Defaults to `0.95`.
#' @param spaghetti Logical. When `TRUE` (and the focal smooth is
#'   one-dimensional, not a surface), individual posterior draws
#'   are returned as an attribute for spaghetti-style overlays.
#' @param surface Logical. For two-dimensional smooths, `TRUE`
#'   (the default) returns a `resolution`-by-`resolution` grid for
#'   surface / heatmap rendering; `FALSE` returns a faceted line
#'   plot at three values of the second covariate (mean +/- 1 SD).
#'   See `facets` for finer control.
#' @param facets Optional positive integer. When `surface = FALSE`
#'   and the smooth has two or more dimensions, controls how many
#'   facet levels of the non-focal covariate(s) to use (default:
#'   `3`, matching brms). Setting `facets = 5` produces 5 evenly
#'   spaced facets across the non-focal range, an mvgam-only knob
#'   for marginaleffects-style multidimensional displays.
#' @param resolution Positive integer. Grid resolution per
#'   covariate dimension. Defaults to `100`.
#' @param too_far Numeric in \[0, 1\]. For surface smooths, grid
#'   points further than this from the training data (measured in
#'   the unit square) are dropped via
#'   [mgcv::exclude.too.far()]. `0` (default) keeps all points.
#' @param ndraws,draw_ids Optional posterior-draw subsetting.
#' @param ... Unused; present for S3 / brms-parity.
#'
#' @return A named list of class `mvgam_conditional_smooths` with
#'   one element per smooth term. Each element is a `data.frame`
#'   with the brms-style summary columns (`estimate__`, `se__`,
#'   `lower__`, `upper__`, `effect1__` (optionally `effect2__`),
#'   `cond__`) plus the focal covariate(s). Per-element attributes
#'   `response`, `effects`, `surface`, `spaghetti`, and `points`
#'   drive the plot method's layout choices (1D ribbon vs 2D
#'   heatmap panel).
#'
#' @seealso \code{\link[brms]{conditional_smooths.brmsfit}},
#'   [posterior_smooths.mvgam()],
#'   [conditional_effects.mvgam()].
#'
#' @author Nicholas J Clark
#'
#' @method conditional_smooths mvgam
#' @export
conditional_smooths.mvgam <- function(x, smooths = NULL,
                                       int_conditions = NULL,
                                       prob = 0.95, spaghetti = FALSE,
                                       surface = TRUE, facets = 3L,
                                       resolution = 100L, too_far = 0,
                                       ndraws = NULL, draw_ids = NULL,
                                       ...) {
  checkmate::assert_class(x, "mvgam")
  checkmate::assert_character(smooths, null.ok = TRUE)
  checkmate::assert_list(int_conditions, null.ok = TRUE)
  checkmate::assert_number(prob, lower = 0, upper = 1)
  checkmate::assert_logical(spaghetti, len = 1L)
  checkmate::assert_logical(surface, len = 1L)
  checkmate::assert_int(facets, lower = 2L)
  checkmate::assert_int(resolution, lower = 2L)
  checkmate::assert_number(too_far, lower = 0, upper = 1)
  terms_list <- mvgam_smooth_terms(x)
  if (length(terms_list) == 0L) {
    stop(insight::format_error(c(
      "This 'mvgam' fit has no smooth terms.",
      i = paste0(
        "Smooth terms are introduced via 's()', 't2()', 'ti()' ",
        "or 'te()' in the observation or trend formula."
      )
    )))
  }
  if (!is.null(smooths)) {
    keep <- vapply(terms_list, function(t) t$term %in% smooths,
                   logical(1L))
    terms_list <- terms_list[keep]
    if (length(terms_list) == 0L) {
      stop(insight::format_error(
        paste0(
          "None of the requested smooth terms were found. ",
          "Use 'smooths(x)' to list the available terms."
        )
      ))
    }
  }
  probs <- c((1 - prob) / 2, 1 - (1 - prob) / 2)
  out <- vector("list", length(terms_list))
  names(out) <- vapply(
    terms_list,
    function(t) paste0("mu: ", t$term, if (t$side == "trend") " (trend)" else ""),
    character(1L)
  )
  # One set of draws for the whole figure. Left as a count, each term
  # in the loop below would subsample on its own and the panels would
  # be drawn from different iterations of the same posterior.
  draw_ids <- resolve_draw_ids(x, ndraws, draw_ids)
  for (i in seq_along(terms_list)) {
    hit <- terms_list[[i]]
    grid_spec <- build_smooth_grid(
      x, hit, surface = surface, facets = facets,
      resolution = resolution, int_conditions = int_conditions,
      too_far = too_far
    )
    eta <- mvgam_smooth_eta(
      x, hit, grid_spec$newdata, draw_ids = draw_ids
    )
    summary_arr <- brms::posterior_summary(
      eta, probs = probs, robust = TRUE
    )
    colnames(summary_arr) <- c("estimate__", "se__",
                                "lower__", "upper__")
    res <- cbind(grid_spec$cond_data, as.data.frame(summary_arr))
    attr(res, "response") <- names(out)[i]
    attr(res, "effects") <- grid_spec$effects
    attr(res, "surface") <- isTRUE(grid_spec$surface)
    attr(res, "spaghetti") <- if (
      isTRUE(spaghetti) && !isTRUE(grid_spec$surface) &&
        length(grid_spec$effects) == 1L
    ) {
      build_spaghetti_data(eta, grid_spec$cond_data,
                            grid_spec$effects)
    } else {
      NULL
    }
    attr(res, "points") <- mvgam_smooth_points(x, hit, grid_spec)
    out[[i]] <- res
  }
  # `mvgam_conditional_smooths` owns its own plot method that
  # renders 1D smooths with the house palette + theme. For 2D /
  # surface cases the plot method reuses brms's plot code by
  # re-classing each per-smooth data.frame internally; no brms
  # class is exposed on the returned object.
  structure(
    out,
    class = c("mvgam_conditional_smooths", "list"),
    smooths_only = TRUE
  )
}


#' Plot or print a mvgam_conditional_smooths object
#'
#' @param x An object of class `mvgam_conditional_smooths`
#'   returned by [conditional_smooths.mvgam()].
#' @param plot Logical. If `TRUE` (default), draws each smooth's
#'   ggplot; otherwise returns the list invisibly for post-processing.
#' @param ask Logical. If `TRUE`, prompts before each new plot when
#'   multiple smooths are drawn to the same device.
#' @param ... Ignored.
#'
#' @return Invisibly returns the list of ggplot objects, one per
#'   smooth term in `x`.
#'
#' @rdname conditional_smooths.mvgam
#' @method plot mvgam_conditional_smooths
#' @export
plot.mvgam_conditional_smooths <- function(x, plot = TRUE,
                                            ask = FALSE, ...) {
  if (length(x) == 0L) return(invisible(x))
  # Lock the palette to the mvgam red scheme for the duration of
  # this call, matching plot.mvgam_forecast / plot.mvgam_stability
  # / plot.mvgam_irf. Any user-side bayesplot::color_scheme_set is
  # restored on exit.
  set_color_scheme_local("red")
  labels <- names(x) %||% rep_len(NA_character_, length(x))
  ggs <- Map(build_mvgam_smooth_plot, x, labels)
  if (isTRUE(plot)) {
    default_ask <- grDevices::devAskNewPage()
    on.exit(grDevices::devAskNewPage(default_ask))
    grDevices::devAskNewPage(ask = isTRUE(ask))
    for (g in ggs) graphics::plot(g)
  }
  invisible(ggs)
}


#' @rdname conditional_smooths.mvgam
#' @method print mvgam_conditional_smooths
#' @export
print.mvgam_conditional_smooths <- function(x, ...) plot(x, ...)


# Internal: split a smooth's panel by condition when it has more
# than one.
#
# A `by`-factor smooth returns one curve per level, stacked in a
# single frame and told apart by `cond__`. Drawn as one group the
# line runs the width of the covariate once per level and returns,
# which comes out as a sawtooth under a ribbon spanning every
# curve's uncertainty at once. brms facets its own
# conditional-effects panels on `cond__`, so the same split is used
# here and the two renderers agree about what a condition is.
#
# Returns NULL for a smooth with one condition, which adds nothing
# to the plot.
#' @noRd
smooth_condition_facet <- function(df) {
  if (!"cond__" %in% names(df) || length(unique(df$cond__)) < 2L) {
    return(NULL)
  }
  ggplot2::facet_wrap(ggplot2::vars(.data[["cond__"]]))
}


# Build one mvgam-themed ggplot from a single smooth's summary
# data.frame. Handles the common 1D case directly with a
# geom_ribbon + geom_line (+ optional spaghetti / points rug);
# falls back to the brms plotter for 2D surface / faceted lines
# so we do not have to reimplement those grids.
#'@noRd
build_mvgam_smooth_plot <- function(df, label) {
  effs <- attr(df, "effects")
  is_surface <- isTRUE(attr(df, "surface"))
  label <- label %||% attr(df, "response") %||% ""
  # 2D or surface smooths: reuse brms's existing plot code by
  # wrapping the single data.frame back into a length-1
  # brms_conditional_effects and delegating. The mvgam theme
  # is applied on top so the panel matches the rest of our
  # dispatcher's output.
  if (length(effs) != 1L || is_surface) {
    single <- structure(
      list(df),
      class = c("brms_conditional_effects", "list"),
      smooths_only = TRUE
    )
    names(single) <- label
    return(plot(single, plot = FALSE)[[1L]] + mvgam_theme())
  }
  # 1D smooth: build the ribbon + median line ourselves so we
  # pick up the active mvgam palette and produce a plot with the
  # house look rather than the brms blue default.
  x_var <- effs[[1L]]
  pal <- mvgam_palette()
  # A smooth over a factor, `s(series, bs = "re")` say, has one grid
  # point per level. A ribbon and a line each need two points before
  # they draw anything, so a panel built from them comes out empty
  # however many levels there are. An interval per level is the shape
  # that has something to show, and it is what brms draws for a
  # categorical conditional effect.
  if (!is.numeric(df[[x_var]])) {
    return(
      ggplot2::ggplot(df, ggplot2::aes(x = .data[[x_var]])) +
        ggplot2::geom_pointrange(
          ggplot2::aes(y = estimate__, ymin = lower__, ymax = upper__),
          colour = pal[5L], linewidth = 0.8, size = 0.4
        ) +
        smooth_condition_facet(df) +
        ggplot2::labs(x = x_var, y = label) +
        mvgam_theme()
    )
  }
  gg <- ggplot2::ggplot(df, ggplot2::aes(x = .data[[x_var]])) +
    ggplot2::geom_ribbon(
      ggplot2::aes(ymin = lower__, ymax = upper__),
      fill = pal[3L], alpha = 0.5
    )
  spaghetti_df <- attr(df, "spaghetti")
  if (!is.null(spaghetti_df) && nrow(spaghetti_df) > 0L) {
    gg <- gg + ggplot2::geom_line(
      data = spaghetti_df,
      ggplot2::aes(
        x = .data[[x_var]], y = value, group = draw__
      ),
      colour = pal[4L], alpha = 0.15, linewidth = 0.35,
      inherit.aes = FALSE
    )
  }
  # Median line uses palette slot 5 to match `mvgam_median_layer`
  # (the shared plot_helpers primitive) so smooth panels sit in
  # the same visual family as the forecast / trend hindcast plots.
  gg +
    ggplot2::geom_line(
      ggplot2::aes(y = estimate__),
      colour = pal[5L], linewidth = 1
    ) +
    smooth_condition_facet(df) +
    ggplot2::labs(x = x_var, y = label) +
    mvgam_theme()
}


#' @importFrom brms conditional_smooths
#' @export
brms::conditional_smooths


#' Enumerate smooth terms in a fitted \pkg{mvgam} model
#'
#' Returns the canonical term labels for every `s()`, `t2()`,
#' `ti()`, or `te()` smooth on either the observation formula or
#' the trend formula of a fitted `mvgam` object. Useful for
#' picking a term to pass to [posterior_smooths.mvgam()] or
#' [conditional_smooths.mvgam()].
#'
#' @param x A fitted `mvgam` object.
#'
#' @return A character vector of canonical smooth labels. Empty
#'   if the fit has no smooth terms.
#'
#' @author Nicholas J Clark
#'
#' @export
smooths.mvgam <- function(x) {
  checkmate::assert_class(x, "mvgam")
  vapply(mvgam_smooth_terms(x), function(t) t$term, character(1L))
}


#' @rdname smooths.mvgam
#' @export
smooths <- function(x) {
  UseMethod("smooths")
}


# ------------------------------------------------------------------
# Internal helpers
# ------------------------------------------------------------------


# Return the brms `bf()` object for the obs or trend side of a
# fitted mvgam. Returns NULL when the requested side has no
# formula.
#'@noRd
mvgam_side_formula <- function(x, side) {
  f <- if (identical(side, "trend")) x$trend_formula else x$formula
  if (is.null(f)) return(NULL)
  if (inherits(f, "brmsformula")) f else brms::bf(f)
}


# Suffix appended to brms-style parameter names for trend-side
# blocks (`Xs_trend`, `bs_trend[k]`, `Zs_<r>_<j>_trend`,
# `s_<r>_<j>_trend[k]`).
#'@noRd
mvgam_side_suffix <- function(side) {
  if (identical(side, "trend")) "_trend" else ""
}


# Extract the canonical brms smooth-term labels for a formula
# and build the matching one-sided smooth-only formula that
# `mgcv::interpret.gam()` can parse into a `smooth.spec` list.
# Returns NULL when the formula has no smooths.
#'@noRd
mvgam_smooth_label_spec <- function(formula, family = NULL) {
  # A formula carrying a family-specific aterm, `y | trials(n) ~ s(x)`
  # on a binomial fit say, only parses if brms knows the family: with
  # none to hand `validate_formula()` assumes gaussian and rejects the
  # aterm. What matters is whether the formula already names a family,
  # not how it is spelled. `mvgam_side_formula()` always returns a
  # `brmsformula`, so testing the class instead would leave every fit
  # reaching this through a side formula with no family at all.
  if (!is.null(family) && !inherits(formula, "mvbrmsformula")) {
    if (inherits(formula, "brmsformula")) {
      if (is.null(formula$family)) {
        formula$family <- family
      }
    } else {
      formula <- brms::bf(formula, family = family)
    }
  }
  # Multivariate fits (mvbind / mvbrmsformula). Calling
  # `brms::brmsterms()` directly on a mvbrmsformula triggers a
  # `validate_formula.mvbrmsformula` pass that rejects
  # `set_rescor(TRUE)` unless each per-response `bf()` carries an
  # explicit gaussian / student family. mvgam users pass `family =`
  # to `mvgam()` instead of inside each `bf()`, so per-response
  # `$family` is NULL and the rescor validator errors. Iterate the
  # per-response `$forms` (each a regular brmsformula), inject the
  # shared family, and union the smooth labels across responses.
  if (inherits(formula, "mvbrmsformula")) {
    per_resp <- lapply(formula$forms, function(bf) {
      if (is.null(bf$family) && !is.null(family)) {
        bf$family <- family
      }
      mvgam_smooth_label_spec(bf, family = family)
    })
    per_resp <- per_resp[!vapply(per_resp, is.null, logical(1L))]
    if (length(per_resp) == 0L) return(NULL)
    labels <- unique(unlist(lapply(per_resp, `[[`, "labels"),
                              use.names = FALSE))
    spec <- unlist(lapply(per_resp, `[[`, "spec"),
                    recursive = FALSE, use.names = FALSE)
    spec <- spec[!duplicated(vapply(spec, function(s) s$label,
                                       character(1L)))]
    return(list(labels = labels, spec = spec))
  }
  bt <- brms::brmsterms(formula)
  sm <- bt$dpars$mu$sm
  if (is.null(sm)) return(NULL)
  brms_labels <- attr(stats::terms(sm), "term.labels")
  if (length(brms_labels) == 0L) return(NULL)
  smooth_form <- stats::as.formula(
    paste0("._mvgam_dummy_ ~ ", paste(brms_labels, collapse = " + "))
  )
  spec <- mgcv::interpret.gam(smooth_form)$smooth.spec
  if (length(spec) != length(brms_labels)) return(NULL)
  list(labels = brms_labels, spec = spec)
}


# Resolve a user-supplied smooth label to its mvgam smooth-term
# descriptor. Accepts both spaced (`"s(z, by = g)"`) and unspaced
# (`"s(z,by=g)"`) variants by normalising whitespace before
# matching, mirroring how brms tolerates either form.
#'@noRd
resolve_mvgam_smooth <- function(x, smooth) {
  terms_list <- mvgam_smooth_terms(x)
  norm <- function(s) gsub("[[:space:]]+", "", s)
  needle <- norm(smooth)
  for (t in terms_list) {
    if (norm(t$term) == needle) {
      return(t)
    }
  }
  available <- vapply(terms_list, function(t) t$term, character(1L))
  stop(insight::format_error(c(
    paste0("Smooth term '", smooth, "' not found in this ",
            "'mvgam' fit."),
    i = paste0(
      "Available smooth terms: ",
      if (length(available) > 0L) {
        paste0("'", available, "'", collapse = ", ")
      } else {
        "<none>"
      },
      "."
    )
  )))
}


# Which family a side of the model is parsed under. The observation
# side carries the fit's own family, and with it any aterm that
# family brings; the latent trend is gaussian whatever the
# observations are.
#'@noRd
mvgam_side_family <- function(x, side) {
  if (identical(side, "trend")) stats::gaussian() else x$family
}


# Enumerate every smooth term across the observation and trend
# formulas. Returns a list; each entry is
# `list(term, side, rows, term_idx, by_var)` where `rows` is the
# vector of smframe-equivalent row indices (one per by-level for
# `s(x, by = factor)` smooths, otherwise length 1) and matches
# the `<row>` suffix in brms-emitted Stan parameter names
# (`Zs_<row>_<j>`, `s_<row>_<j>[k]`).
#'@noRd
mvgam_smooth_terms <- function(x) {
  checkmate::assert_class(x, "mvgam")
  out <- list()
  obs_idx <- mvgam_smooth_index(
    x$formula, mvgam_side_data(x, "obs"),
    family = mvgam_side_family(x, "obs")
  )
  if (!is.null(obs_idx)) {
    for (term in unique(obs_idx$term)) {
      sub <- obs_idx[obs_idx$term == term, , drop = FALSE]
      out[[length(out) + 1L]] <- list(
        term = term, side = "obs",
        rows = sub$row, term_idx = sub$term_idx[1L],
        by_var = sub$by_var[1L]
      )
    }
  }
  trend_bf <- mvgam_side_formula(x, "trend")
  if (!is.null(trend_bf)) {
    # The trend side is read on its own grid, not the observation
    # frame. A `by` variable the trend design carries -- `.trend`
    # under `by = lv_axis()` -- is absent from the observation
    # frame, so looking for it there found nothing, the term was
    # never expanded per by-level, and only the first level's
    # smooth was ever evaluated. The other level came back as a
    # flat curve with no posterior width.
    trend_idx <- mvgam_smooth_index(
      trend_bf, mvgam_side_data(x, "trend"),
      family = mvgam_side_family(x, "trend")
    )
    if (!is.null(trend_idx)) {
      for (term in unique(trend_idx$term)) {
        sub <- trend_idx[trend_idx$term == term, , drop = FALSE]
        out[[length(out) + 1L]] <- list(
          term = term, side = "trend",
          rows = sub$row, term_idx = sub$term_idx[1L],
          by_var = sub$by_var[1L]
        )
      }
    }
  }
  out
}


# Build the smframe-equivalent index for one side of the model.
# Walks `mgcv::interpret.gam()$smooth.spec` to obtain `by`-factor
# expansion and `brms::brmsterms()` for the canonical term labels.
# Returns NULL if the formula has no smooths.
#'@noRd
mvgam_smooth_index <- function(formula, data, family = NULL) {
  ls <- mvgam_smooth_label_spec(formula, family = family)
  if (is.null(ls)) return(NULL)
  brms_labels <- ls$labels
  spec <- ls$spec
  out <- list()
  row_idx <- 0L
  for (i in seq_along(spec)) {
    s <- spec[[i]]
    by_var <- if (length(s$by) == 0L ||
                  is.na(s$by) || identical(s$by, "NA")) {
      NA_character_
    } else {
      s$by
    }
    expand <- FALSE
    if (!is.na(by_var) && by_var %in% names(data)) {
      by_col <- data[[by_var]]
      if (is.character(by_col)) by_col <- factor(by_col)
      if (is.factor(by_col)) {
        for (lv in levels(by_col)) {
          row_idx <- row_idx + 1L
          out[[length(out) + 1L]] <- data.frame(
            row = row_idx, term = brms_labels[i],
            by_var = by_var, by_level = lv,
            term_idx = i, stringsAsFactors = FALSE
          )
        }
        expand <- TRUE
      }
    }
    if (!expand) {
      row_idx <- row_idx + 1L
      out[[length(out) + 1L]] <- data.frame(
        row = row_idx, term = brms_labels[i],
        by_var = if (is.na(by_var)) NA_character_ else by_var,
        by_level = NA_character_,
        term_idx = i, stringsAsFactors = FALSE
      )
    }
  }
  if (length(out) == 0L) return(NULL)
  do.call(rbind, out)
}


#' The frame one side of the model was fitted on
#'
#' A smooth is drawn over, and evaluated on, the frame its own side
#' carries. The trend side runs on the trend grid rather than the
#' observation one, and under `by = lv_axis()` that grid holds one
#' row per (time, latent factor) plus the `.trend` factor the smooth
#' is split by. The observation frame has no such column, so reading
#' it leaves the only smooth such a model has unevaluable: the grid
#' builder produces no rows and the evaluator is refused by brms for
#' a variable it cannot find.
#'
#' The observation side is the exception, and deliberately so: its
#' frame is the one the user supplied, which is what `object$data`
#' already holds. Only the trend side runs on a frame of its own, so
#' only the trend side needs to be redirected.
#'
#' Answering this in one place keeps the grid a smooth is drawn over
#' and the grid it is evaluated on the same frame.
#'
#' @param object A fitted `mvgam` object
#' @param side Either `"trend"` or `"obs"`
#' @return The model frame that side was fitted on
#' @noRd
mvgam_side_data <- function(object, side) {
  if (!identical(side, "trend")) {
    return(object$data)
  }
  # A trend model reaches here without a stored frame only on an
  # object assembled by hand, and the user's frame is the closest
  # thing to a trend grid such an object has.
  object$trend_model$data %||% object$data
}


# Core compute: posterior draws of one smooth term's contribution
# to the linear predictor at the supplied prediction grid. Used by
# both `posterior_smooths.mvgam` and `conditional_smooths.mvgam`.
#'@noRd
mvgam_smooth_eta <- function(object, hit, newdata,
                              draw_ids = NULL) {
  side <- hit$side
  side_model <- if (identical(side, "trend")) {
    object$trend_model
  } else {
    object$obs_model
  }
  if (is.null(newdata)) {
    newdata <- mvgam_side_data(object, side)
  }
  side_form <- mvgam_side_formula(object, side)
  suffix <- mvgam_side_suffix(side)
  # Backfill any missing response column so brms::standata's
  # validate_newdata accepts the grid. Family-aware dummy mirrors
  # brms::check_response = FALSE.
  resp <- unname(response_columns(side_form)[1L])
  if (!(resp %in% names(newdata))) {
    fam <- object$family
    if (!inherits(fam, "brmsfamily")) {
      fam <- brms::brmsfamily(fam$family, link = fam$link)
    }
    newdata[[resp]] <- get_safe_dummy_value(fam)
  }
  # brms::standata routes through the brmsfit-shaped side model's
  # stored basis (computed at fit time), so PredictMat handles
  # any newdata grid, sparse or dense, without re-running
  # smoothCon. This is exactly what brms's posterior_smooths does.
  #
  # Pass `check_response = FALSE` and `internal = TRUE` so brms
  # skips response + aterm validation on `newdata`, which matches
  # what `brms:::posterior_smooths.btl` does and prevents
  # family-specific aterm columns (e.g. `| trials(N)` for
  # binomial fits) from raising errors when the caller's grid
  # doesn't carry those columns.
  sd_new <- brms::standata(
    side_model, newdata = newdata,
    check_response = FALSE, internal = TRUE
  )
  # `side_model` is a standalone brmsfit (either the obs-side or
  # the trend-side model), so its own `standata()` returns bare
  # slot names (`Xs`, `Zs_r_k`) with no `_trend` / `_obs` suffix.
  # The suffix belongs only on the *composed* mvgam draws, where
  # `bs_...` and `s_r_k_...` coefficients carry the side tag so
  # obs and trend smooths can coexist in one draws matrix. We
  # read the design matrices with the bare keys and re-append
  # the suffix when we alias into the composed draws below.
  Xs_full <- sd_new[["Xs"]]
  smcols <- attr(Xs_full, "smcols")
  Xs_focal <- if (!is.null(Xs_full) && length(smcols) > 0L) {
    cols <- unlist(smcols[hit$rows])
    if (length(cols) > 0L) {
      out <- Xs_full[, cols, drop = FALSE]
      colnames(out) <- paste0(
        "bs_", colnames(Xs_full)[cols], suffix
      )
      out
    } else {
      NULL
    }
  } else {
    NULL
  }
  zs_blocks <- list()
  for (r in hit$rows) {
    keys <- grep(
      sprintf("^Zs_%d_\\d+$", r),
      names(sd_new), value = TRUE
    )
    for (k in keys) {
      # Add the side suffix when aliasing into the composed
      # mvgam draws matrix, since `s_r_k_...trend` etc. live
      # there whereas `sd_new` uses the bare form `Zs_r_k`.
      zs_blocks[[length(zs_blocks) + 1L]] <- list(
        Z = sd_new[[k]],
        s_pattern = paste0(sub("^Zs_", "s_", k), suffix)
      )
    }
  }
  drws <- extract_mvgam_draws(object)
  drws_mat <- posterior::as_draws_matrix(drws)
  drws_mat <- subset_draws_rows(drws_mat, draw_ids = draw_ids)
  eta <- matrix(0, nrow = nrow(drws_mat),
                 ncol = nrow(newdata))
  if (!is.null(Xs_focal) && ncol(Xs_focal) > 0L) {
    bs_aliases <- colnames(Xs_focal)
    missing_bs <- setdiff(bs_aliases, colnames(drws_mat))
    if (length(missing_bs) > 0L) {
      stop(insight::format_error(c(
        paste0(
          "Internal: expected smooth fixed-effect ",
          "coefficients not found in the cached draws."
        ),
        x = paste0(
          "Missing: ",
          paste0("'", missing_bs, "'", collapse = ", ")
        )
      )))
    }
    bs_draws <- drws_mat[, bs_aliases, drop = FALSE]
    eta <- eta + bs_draws %*% t(Xs_focal)
  }
  for (blk in zs_blocks) {
    pattern <- paste0("^", gsub("([\\[\\]])", "\\\\\\1",
                                  blk$s_pattern), "\\[")
    s_names <- grep(pattern, colnames(drws_mat),
                     value = TRUE)
    if (length(s_names) == 0L) next
    s_draws <- drws_mat[, s_names, drop = FALSE]
    eta <- eta + s_draws %*% t(blk$Z)
  }
  eta
}




# Build the prediction grid for one smooth term. Mirrors brms's
# conditional_smooths grid logic: 1D smooths sweep the focal
# covariate; 2D smooths get a surface grid by default, or a
# faceted-line layout when `surface = FALSE` (with `facets`
# controlling the facet count); >2D smooths recursively move
# non-focal covariates into the by-variable set so the facet
# strip degrades to a discrete grouping.
#'@noRd
build_smooth_grid <- function(x, hit, surface, facets, resolution,
                                int_conditions, too_far) {
  mf <- mvgam_side_data(x, hit$side)
  side_form_bf <- mvgam_side_formula(x, hit$side)
  side_form <- side_form_bf$formula
  spec <- mvgam_smooth_label_spec(
    side_form_bf, family = mvgam_side_family(x, hit$side)
  )$spec[[hit$term_idx]]
  covars <- spec$term
  byvars <- if (!is.na(hit$by_var) && !identical(hit$by_var, "NA")) {
    hit$by_var
  } else {
    character(0L)
  }
  # Promote excess covariates beyond the first two into facet
  # variables to keep the plot dispatch sensible.
  if (length(covars) > 2L) {
    byvars <- c(covars[-(1:2)], byvars)
    covars <- covars[1:2]
  }
  is_numeric <- vapply(covars, function(cv) {
    is.numeric(mf[[cv]])
  }, logical(1L))
  values <- stats::setNames(vector("list", length(covars)), covars)
  for (i in seq_along(covars)) {
    cv <- covars[i]
    if (!is.null(int_conditions) && cv %in% names(int_conditions)) {
      ic <- int_conditions[[cv]]
      if (is.function(ic)) ic <- ic(mf[[cv]])
      values[[cv]] <- ic
    } else if (is_numeric[i]) {
      if (i == 2L && !isTRUE(surface)) {
        m <- mean(mf[[cv]], na.rm = TRUE)
        s <- stats::sd(mf[[cv]], na.rm = TRUE)
        if (facets <= 1L) {
          values[[cv]] <- m
        } else {
          q <- seq(-1, 1, length.out = facets)
          values[[cv]] <- m + q * s
        }
      } else {
        values[[cv]] <- seq(
          min(mf[[cv]], na.rm = TRUE),
          max(mf[[cv]], na.rm = TRUE),
          length.out = resolution
        )
      }
    } else {
      values[[cv]] <- levels(factor(mf[[cv]]))
    }
  }
  for (cv in byvars) {
    if (!is.null(int_conditions) && cv %in% names(int_conditions)) {
      ic <- int_conditions[[cv]]
      if (is.function(ic)) ic <- ic(mf[[cv]])
      values[[cv]] <- ic
    } else if (is.numeric(mf[[cv]])) {
      m <- mean(mf[[cv]], na.rm = TRUE)
      s <- stats::sd(mf[[cv]], na.rm = TRUE)
      values[[cv]] <- m + seq(-1, 1, length.out = facets) * s
    } else {
      values[[cv]] <- levels(factor(mf[[cv]]))
    }
  }
  grid <- expand.grid(values, stringsAsFactors = FALSE)
  # Drop grid points too far from the training data on a 2D
  # surface (brms-parity).
  if (length(covars) == 2L && isTRUE(surface) && too_far > 0) {
    ex <- mgcv::exclude.too.far(
      g1 = grid[[covars[1L]]], g2 = grid[[covars[2L]]],
      d1 = mf[[covars[1L]]], d2 = mf[[covars[2L]]],
      dist = too_far
    )
    grid <- grid[!ex, , drop = FALSE]
  }
  # Backfill non-focal covariates and the response with reasonable
  # defaults so brms::standata can build the basis matrices.
  newdata <- backfill_smooth_grid(grid, x, side_form, covars, byvars)
  cond_data <- grid
  cond_data$effect1__ <- cond_data[[covars[1L]]]
  if (length(covars) == 2L) {
    if (isTRUE(surface)) {
      cond_data$effect2__ <- cond_data[[covars[2L]]]
    } else {
      lvls <- sort(unique(cond_data[[covars[2L]]]), decreasing = TRUE)
      cond_data$effect2__ <- factor(
        round(cond_data[[covars[2L]]], 3L), levels = round(lvls, 3L)
      )
    }
  }
  if (length(byvars) > 0L) {
    cond_data$cond__ <- factor(do.call(
      paste, c(cond_data[byvars], list(sep = " : "))
    ))
  } else {
    cond_data$cond__ <- factor(1L)
  }
  list(
    newdata = newdata, cond_data = cond_data,
    effects = covars, surface = isTRUE(surface) &&
      length(covars) == 2L
  )
}


# Whether every value a numeric column holds is a whole number.
# `is.integer()` is not the question: a column read from a data
# frame is usually double, and what matters is the value rather
# than the storage type.
#'@noRd
is_integer_valued <- function(col) {
  col <- col[!is.na(col)]
  is.numeric(col) && length(col) > 0L && all(col == round(col))
}


# Backfill the prediction-grid `data.frame` so brms::standata can
# build basis matrices. Non-focal covariates get their training
# median (numeric) or first level (factor); the response is set
# to a dummy value because the basis matrices are response-free.
#'@noRd
backfill_smooth_grid <- function(grid, x, side_form, covars, byvars) {
  mf <- x$data
  resp <- unname(response_columns(side_form)[1L])
  # Strip the response from the backfill set: the dummy gets a
  # family-aware value via `mvgam_smooth_eta`. Setting it to the
  # training median here can violate family bounds (e.g.
  # numeric median fails the Poisson integer check).
  non_focal <- setdiff(all.vars(side_form), c(covars, byvars, resp))
  for (cv in non_focal) {
    if (cv %in% names(mf)) {
      col <- mf[[cv]]
      grid[[cv]] <- if (is.numeric(col)) {
        # A median lands between two observations whenever the column
        # has an even count, which an integer-valued covariate cannot
        # represent: the denominator of a `trials()` term comes back
        # as 179.5 and brms refuses a fractional number of trials.
        # Rounding is the better grid value for such a column either
        # way, and none of these reach a design matrix.
        med <- stats::median(col, na.rm = TRUE)
        if (is_integer_valued(col)) round(med) else med
      } else if (is.factor(col)) {
        factor(levels(col)[1L], levels = levels(col))
      } else {
        col[1L]
      }
    }
  }
  if (resp %in% names(grid)) {
    grid[[resp]] <- NULL
  }
  grid
}


# Build the spaghetti-overlay data.frame brms's plot dispatch
# consumes: one row per (draw, grid_point) with columns
# (effect1__, estimate__, sample__).
#'@noRd
build_spaghetti_data <- function(eta, cond_data, effects) {
  n_draws <- nrow(eta)
  n_grid <- ncol(eta)
  out <- data.frame(
    effect1__ = rep(cond_data[[effects[1L]]], times = n_draws),
    estimate__ = as.numeric(t(eta)),
    sample__ = factor(rep(seq_len(n_draws), each = n_grid))
  )
  out
}


# Extract the training-data points the plot method overlays.
# Returns the covariate values from the training data for the
# focal smooth, restricted to the by-factor level (when present)
# so the overlay tracks the corresponding facet.
#'@noRd
mvgam_smooth_points <- function(x, hit, grid_spec) {
  mf <- x$data
  effects <- grid_spec$effects
  if (any(!effects %in% names(mf))) {
    return(data.frame())
  }
  out <- data.frame(mf[, effects, drop = FALSE])
  colnames(out) <- paste0("effect", seq_along(effects), "__")
  out
}
