# Implementation of `posterior_smooths.mvgam` and
# `conditional_smooths.mvgam`. The mvgam stancode is generated by
# brms's own machinery, so the parameter blocks for `s(...)`,
# `t2(...)`, `ti(...)`, `te(...)` terms follow brms's positional
# Stan-name conventions exactly:
#   * `Xs` (or `Xs_trend`)            - fixed unpenalised basis
#   * `Zs_<row>_<j>` (`_trend`)       - per-penalty random-effect basis
#   * `bs[k]` (`bs_trend[k]`)         - fixed-effect coefficients
#   * `s_<row>_<j>[k]` (`_trend`)     - random-effect coefficients
#   * `sds_<row>[k]` (`_trend`)       - smoothing standard deviations
# `<row>` indexes the smframe (one row per smooth term, expanded
# per by-level for `s(x, by = factor)`). The fixed-effect block
# also carries an `attr(Xs, "smcols")` list that maps each smframe
# row to its columns in `Xs`. By-factor smooths produce consecutive
# rows, one per level of the by-factor; their `smcols` entries
# together span the focal smooth.
#
# The aliaser in `mvgam_beta_aliases()` renames `bs[k]` to
# `bs_<colname>` (and `bs_trend[k]` to `bs_<colname>_trend`) so we
# can fetch coefficients by their brms-native names rather than by
# raw positional index. Random-effect coefficients stay under
# their positional `s_<row>_<j>[k]` names because brms does too.


#' Compute posterior draws of a smooth term in a fitted
#' \pkg{mvgam} model
#'
#' Returns the posterior draws of a single smooth term evaluated
#' at the supplied prediction grid, matching the shape of
#' [brms::posterior_smooths()]. Supports any smooth declared by
#' `s()`, `t2()`, `ti()`, or `te()` on either the observation
#' formula or the trend formula, including `by = factor`
#' expansion.
#'
#' @param object A fitted `mvgam` object.
#' @param smooth Character string naming the smooth term as it
#'   appears in the formula (e.g. `"s(x)"`,
#'   `"s(z, by = group)"`, `"t2(x, y)"`). Use
#'   [smooths.mvgam()] to enumerate the available terms.
#' @param newdata Optional `data.frame` to evaluate the smooth
#'   at. `NULL` (the default) uses the training data.
#' @param resp,dpar,nlpar Retained for brms-parity. mvgam fits
#'   are currently univariate on a single distributional
#'   parameter; supplying non-`NULL` values raises an error.
#' @param ndraws,draw_ids Optional posterior-draw subsetting,
#'   matching the [brms::posterior_smooths()] semantics.
#' @param ... Unused; present for S3 / brms-parity.
#'
#' @return A numeric matrix of dimension
#'   \[n_draws x n_grid_points\] containing the posterior draws
#'   of the smooth term's contribution to the linear predictor.
#'
#' @details
#' The smooth's contribution is computed as
#' `Xs_focal %*% bs_focal + sum_j Zs_j %*% s_j` per draw, where
#' the basis matrices come from `brms::standata()` evaluated on
#' `newdata`, and the coefficients come from the cached posterior
#' draws (already routed through the mvgam aliaser).
#'
#' For trend-side smooths the same logic applies against the
#' `_trend` parameter block.
#'
#' @seealso [brms::posterior_smooths()],
#'   [conditional_smooths.mvgam()], [smooths.mvgam()].
#'
#' @author Nicholas J Clark
#'
#' @examples
#' \donttest{
#' set.seed(1)
#' sim <- sim_mvgam(family = gaussian())
#' mod <- mvgam(
#'   y ~ 1 + s(season, bs = "cc"),
#'   trend_model = AR(),
#'   data = sim$data_train,
#'   family = gaussian(),
#'   chains = 2,
#'   silent = 2
#' )
#' eta <- posterior_smooths(mod, smooth = "s(season,bs=\"cc\")")
#' dim(eta)
#' }
#'
#' @method posterior_smooths mvgam
#' @export
posterior_smooths.mvgam <- function(object, smooth, newdata = NULL,
                                     resp = NULL, dpar = NULL, nlpar = NULL,
                                     ndraws = NULL, draw_ids = NULL, ...) {
  checkmate::assert_class(object, "mvgam")
  checkmate::assert_string(smooth)
  if (!is.null(newdata)) {
    checkmate::assert_data_frame(newdata, min.rows = 1L)
  }
  if (!is.null(ndraws)) {
    checkmate::assert_int(ndraws, lower = 1L)
  }
  if (!is.null(draw_ids)) {
    checkmate::assert_integerish(draw_ids, lower = 1L, min.len = 1L)
  }
  if (!is.null(resp) || !is.null(dpar) || !is.null(nlpar)) {
    stop(insight::format_error(c(
      paste0(
        "'resp', 'dpar' and 'nlpar' are accepted for ",
        "brms-parity but not yet supported on 'mvgam' fits."
      ),
      i = paste0(
        "mvgam fits are currently univariate on a single ",
        "distributional parameter."
      )
    )))
  }
  hit <- resolve_mvgam_smooth(object, smooth)
  mvgam_smooth_eta(
    object, hit, newdata, ndraws = ndraws, draw_ids = draw_ids
  )
}


#' @importFrom brms posterior_smooths
#' @export
brms::posterior_smooths


#' Marginal smooth-effect plots for a fitted \pkg{mvgam} model
#'
#' Compute and display posterior conditional effects for every
#' smooth term in a fitted `mvgam` object, matching the shape of
#' \code{\link[brms]{conditional_smooths.brmsfit}}. Returns a named list of
#' `data.frame`s with the brms-style `estimate__` / `lower__` /
#' `upper__` / `effect1__` / `effect2__` / `cond__` columns and
#' inherits the `brms_conditional_effects` class so brms's
#' `plot.brms_conditional_effects()` method works
#' out-of-the-box.
#'
#' @param x A fitted `mvgam` object.
#' @param smooths Optional character vector restricting which
#'   smooth terms to compute. `NULL` (default) returns every
#'   smooth on both the observation and trend formulas.
#' @param int_conditions Optional named list. Each name is a
#'   covariate; each value either a numeric vector of conditioning
#'   values or a function applied to the original covariate. Used
#'   for non-focal covariates that appear in by-factor faceting.
#' @param prob Numeric in `(0, 1)`. The credible-interval mass
#'   reported via `lower__` / `upper__`. Defaults to `0.95`.
#' @param spaghetti Logical. When `TRUE` (and the focal smooth is
#'   one-dimensional, not a surface), individual posterior draws
#'   are returned as an attribute for spaghetti-style overlays.
#' @param surface Logical. For two-dimensional smooths, `TRUE`
#'   (the default) returns a `resolution`-by-`resolution` grid for
#'   surface / heatmap rendering; `FALSE` returns a faceted line
#'   plot at three values of the second covariate (mean +/- 1 SD).
#'   See `facets` for finer control.
#' @param facets Optional positive integer. When `surface = FALSE`
#'   and the smooth has two or more dimensions, controls how many
#'   facet levels of the non-focal covariate(s) to use (default:
#'   `3`, matching brms). Setting `facets = 5` produces 5 evenly
#'   spaced facets across the non-focal range — an mvgam-only knob
#'   for marginaleffects-style multidimensional displays.
#' @param resolution Positive integer. Grid resolution per
#'   covariate dimension. Defaults to `100`.
#' @param too_far Numeric in \[0, 1\]. For surface smooths, grid
#'   points further than this from the training data (measured in
#'   the unit square) are dropped via
#'   [mgcv::exclude.too.far()]. `0` (default) keeps all points.
#' @param ndraws,draw_ids Optional posterior-draw subsetting.
#' @param ... Unused; present for S3 / brms-parity.
#'
#' @return A named list with one element per smooth term. Each
#'   element is a `data.frame` with the brms-style summary columns
#'   (`estimate__`, `se__`, `lower__`, `upper__`,
#'   `effect1__` (optionally `effect2__`), `cond__`) plus the focal
#'   covariate(s). Attributes `response`, `effects`,
#'   `surface`, `spaghetti`, and `points` are populated for the
#'   existing brms plot dispatch. The returned object carries the
#'   `brms_conditional_effects` class.
#'
#' @seealso \code{\link[brms]{conditional_smooths.brmsfit}},
#'   [posterior_smooths.mvgam()],
#'   [conditional_effects.mvgam()].
#'
#' @author Nicholas J Clark
#'
#' @examples
#' \donttest{
#' set.seed(1)
#' sim <- sim_mvgam(family = gaussian())
#' mod <- mvgam(
#'   y ~ 1 + s(season, bs = "cc"),
#'   trend_model = AR(),
#'   data = sim$data_train,
#'   family = gaussian(),
#'   chains = 2,
#'   silent = 2
#' )
#' cs <- conditional_smooths(mod)
#' plot(cs)
#' }
#'
#' @method conditional_smooths mvgam
#' @export
conditional_smooths.mvgam <- function(x, smooths = NULL,
                                       int_conditions = NULL,
                                       prob = 0.95, spaghetti = FALSE,
                                       surface = TRUE, facets = 3L,
                                       resolution = 100L, too_far = 0,
                                       ndraws = NULL, draw_ids = NULL,
                                       ...) {
  checkmate::assert_class(x, "mvgam")
  checkmate::assert_character(smooths, null.ok = TRUE)
  checkmate::assert_list(int_conditions, null.ok = TRUE)
  checkmate::assert_number(prob, lower = 0, upper = 1)
  checkmate::assert_logical(spaghetti, len = 1L)
  checkmate::assert_logical(surface, len = 1L)
  checkmate::assert_int(facets, lower = 2L)
  checkmate::assert_int(resolution, lower = 2L)
  checkmate::assert_number(too_far, lower = 0, upper = 1)
  terms_list <- mvgam_smooth_terms(x)
  if (length(terms_list) == 0L) {
    stop(insight::format_error(c(
      "This 'mvgam' fit has no smooth terms.",
      i = paste0(
        "Smooth terms are introduced via 's()', 't2()', 'ti()' ",
        "or 'te()' in the observation or trend formula."
      )
    )))
  }
  if (!is.null(smooths)) {
    keep <- vapply(terms_list, function(t) t$term %in% smooths,
                   logical(1L))
    terms_list <- terms_list[keep]
    if (length(terms_list) == 0L) {
      stop(insight::format_error(
        paste0(
          "None of the requested smooth terms were found. ",
          "Use 'smooths(x)' to list the available terms."
        )
      ))
    }
  }
  probs <- c((1 - prob) / 2, 1 - (1 - prob) / 2)
  out <- vector("list", length(terms_list))
  names(out) <- vapply(
    terms_list,
    function(t) paste0("mu: ", t$term, if (t$side == "trend") " (trend)" else ""),
    character(1L)
  )
  for (i in seq_along(terms_list)) {
    hit <- terms_list[[i]]
    grid_spec <- build_smooth_grid(
      x, hit, surface = surface, facets = facets,
      resolution = resolution, int_conditions = int_conditions,
      too_far = too_far
    )
    eta <- mvgam_smooth_eta(
      x, hit, grid_spec$newdata,
      ndraws = ndraws, draw_ids = draw_ids
    )
    summary_arr <- brms::posterior_summary(
      eta, probs = probs, robust = TRUE
    )
    colnames(summary_arr) <- c("estimate__", "se__",
                                "lower__", "upper__")
    res <- cbind(grid_spec$cond_data, as.data.frame(summary_arr))
    attr(res, "response") <- names(out)[i]
    attr(res, "effects") <- grid_spec$effects
    attr(res, "surface") <- isTRUE(grid_spec$surface)
    attr(res, "spaghetti") <- if (
      isTRUE(spaghetti) && !isTRUE(grid_spec$surface) &&
        length(grid_spec$effects) == 1L
    ) {
      build_spaghetti_data(eta, grid_spec$cond_data,
                            grid_spec$effects)
    } else {
      NULL
    }
    attr(res, "points") <- mvgam_smooth_points(x, hit, grid_spec)
    out[[i]] <- res
  }
  structure(
    out,
    class = c("brms_conditional_effects", "list"),
    smooths_only = TRUE
  )
}


#' @importFrom brms conditional_smooths
#' @export
brms::conditional_smooths


#' Enumerate smooth terms in a fitted \pkg{mvgam} model
#'
#' Returns the canonical term labels for every `s()`, `t2()`,
#' `ti()`, or `te()` smooth on either the observation formula or
#' the trend formula of a fitted `mvgam` object. Useful for
#' picking a term to pass to [posterior_smooths.mvgam()] or
#' [conditional_smooths.mvgam()].
#'
#' @param x A fitted `mvgam` object.
#'
#' @return A character vector of canonical smooth labels. Empty
#'   if the fit has no smooth terms.
#'
#' @author Nicholas J Clark
#'
#' @examples
#' \donttest{
#' sim <- sim_mvgam(family = gaussian())
#' mod <- mvgam(y ~ 1 + s(season, bs = "cc"),
#'              trend_model = AR(), data = sim$data_train,
#'              family = gaussian(), chains = 2, silent = 2)
#' smooths(mod)
#' }
#'
#' @export
smooths.mvgam <- function(x) {
  checkmate::assert_class(x, "mvgam")
  vapply(mvgam_smooth_terms(x), function(t) t$term, character(1L))
}


#' @export
smooths <- function(x) {
  UseMethod("smooths")
}


# ------------------------------------------------------------------
# Internal helpers
# ------------------------------------------------------------------


# Return the brms `bf()` object for the obs or trend side of a
# fitted mvgam. Returns NULL when the requested side has no
# formula.
#'@noRd
mvgam_side_formula <- function(x, side) {
  f <- if (identical(side, "trend")) x$trend_formula else x$formula
  if (is.null(f)) return(NULL)
  if (inherits(f, "brmsformula")) f else brms::bf(f)
}


# Suffix appended to brms-style parameter names for trend-side
# blocks (`Xs_trend`, `bs_trend[k]`, `Zs_<r>_<j>_trend`,
# `s_<r>_<j>_trend[k]`).
#'@noRd
mvgam_side_suffix <- function(side) {
  if (identical(side, "trend")) "_trend" else ""
}


# Extract the canonical brms smooth-term labels for a formula
# and build the matching one-sided smooth-only formula that
# `mgcv::interpret.gam()` can parse into a `smooth.spec` list.
# Returns NULL when the formula has no smooths.
#'@noRd
mvgam_smooth_label_spec <- function(formula, family = NULL) {
  # When the caller's formula carries family-specific aterms (e.g.
  # `y | trials(trials) ~ s(x)` on a binomial fit) but is a plain
  # R formula rather than a `brmsformula`, brms's `brmsterms.default`
  # falls through to a `validate_formula(family = gaussian())` call
  # and rejects the aterm. Wrap the formula in `brms::bf()` with
  # the supplied family so brms's parser knows trials() is valid.
  if (!is.null(family) && !inherits(formula, "brmsformula") &&
      !inherits(formula, "mvbrmsformula")) {
    formula <- brms::bf(formula, family = family)
  }
  bt <- brms::brmsterms(formula)
  sm <- bt$dpars$mu$sm
  if (is.null(sm)) return(NULL)
  brms_labels <- attr(stats::terms(sm), "term.labels")
  if (length(brms_labels) == 0L) return(NULL)
  smooth_form <- stats::as.formula(
    paste0("._mvgam_dummy_ ~ ", paste(brms_labels, collapse = " + "))
  )
  spec <- mgcv::interpret.gam(smooth_form)$smooth.spec
  if (length(spec) != length(brms_labels)) return(NULL)
  list(labels = brms_labels, spec = spec)
}


# Resolve a user-supplied smooth label to its mvgam smooth-term
# descriptor. Accepts both spaced (`"s(z, by = g)"`) and unspaced
# (`"s(z,by=g)"`) variants by normalising whitespace before
# matching, mirroring how brms tolerates either form.
#'@noRd
resolve_mvgam_smooth <- function(x, smooth) {
  terms_list <- mvgam_smooth_terms(x)
  norm <- function(s) gsub("[[:space:]]+", "", s)
  needle <- norm(smooth)
  for (t in terms_list) {
    if (norm(t$term) == needle) {
      return(t)
    }
  }
  available <- vapply(terms_list, function(t) t$term, character(1L))
  stop(insight::format_error(c(
    paste0("Smooth term '", smooth, "' not found in this ",
            "'mvgam' fit."),
    i = paste0(
      "Available smooth terms: ",
      if (length(available) > 0L) {
        paste0("'", available, "'", collapse = ", ")
      } else {
        "<none>"
      },
      "."
    )
  )))
}


# Enumerate every smooth term across the observation and trend
# formulas. Returns a list; each entry is
# `list(term, side, rows, term_idx, by_var)` where `rows` is the
# vector of smframe-equivalent row indices (one per by-level for
# `s(x, by = factor)` smooths, otherwise length 1) and matches
# the `<row>` suffix in brms-emitted Stan parameter names
# (`Zs_<row>_<j>`, `s_<row>_<j>[k]`).
#'@noRd
mvgam_smooth_terms <- function(x) {
  checkmate::assert_class(x, "mvgam")
  out <- list()
  obs_idx <- mvgam_smooth_index(
    x$formula, x$data, family = x$family
  )
  if (!is.null(obs_idx)) {
    for (term in unique(obs_idx$term)) {
      sub <- obs_idx[obs_idx$term == term, , drop = FALSE]
      out[[length(out) + 1L]] <- list(
        term = term, side = "obs",
        rows = sub$row, term_idx = sub$term_idx[1L],
        by_var = sub$by_var[1L]
      )
    }
  }
  trend_bf <- mvgam_side_formula(x, "trend")
  if (!is.null(trend_bf)) {
    # Trend latent process is gaussian regardless of obs family.
    trend_idx <- mvgam_smooth_index(
      trend_bf, x$data, family = stats::gaussian()
    )
    if (!is.null(trend_idx)) {
      for (term in unique(trend_idx$term)) {
        sub <- trend_idx[trend_idx$term == term, , drop = FALSE]
        out[[length(out) + 1L]] <- list(
          term = term, side = "trend",
          rows = sub$row, term_idx = sub$term_idx[1L],
          by_var = sub$by_var[1L]
        )
      }
    }
  }
  out
}


# Build the smframe-equivalent index for one side of the model.
# Walks `mgcv::interpret.gam()$smooth.spec` to obtain `by`-factor
# expansion and `brms::brmsterms()` for the canonical term labels.
# Returns NULL if the formula has no smooths.
#'@noRd
mvgam_smooth_index <- function(formula, data, family = NULL) {
  ls <- mvgam_smooth_label_spec(formula, family = family)
  if (is.null(ls)) return(NULL)
  brms_labels <- ls$labels
  spec <- ls$spec
  out <- list()
  row_idx <- 0L
  for (i in seq_along(spec)) {
    s <- spec[[i]]
    by_var <- if (length(s$by) == 0L ||
                  is.na(s$by) || identical(s$by, "NA")) {
      NA_character_
    } else {
      s$by
    }
    expand <- FALSE
    if (!is.na(by_var) && by_var %in% names(data)) {
      by_col <- data[[by_var]]
      if (is.character(by_col)) by_col <- factor(by_col)
      if (is.factor(by_col)) {
        for (lv in levels(by_col)) {
          row_idx <- row_idx + 1L
          out[[length(out) + 1L]] <- data.frame(
            row = row_idx, term = brms_labels[i],
            by_var = by_var, by_level = lv,
            term_idx = i, stringsAsFactors = FALSE
          )
        }
        expand <- TRUE
      }
    }
    if (!expand) {
      row_idx <- row_idx + 1L
      out[[length(out) + 1L]] <- data.frame(
        row = row_idx, term = brms_labels[i],
        by_var = if (is.na(by_var)) NA_character_ else by_var,
        by_level = NA_character_,
        term_idx = i, stringsAsFactors = FALSE
      )
    }
  }
  if (length(out) == 0L) return(NULL)
  do.call(rbind, out)
}


# Core compute: posterior draws of one smooth term's contribution
# to the linear predictor at the supplied prediction grid. Used by
# both `posterior_smooths.mvgam` and `conditional_smooths.mvgam`.
#'@noRd
mvgam_smooth_eta <- function(object, hit, newdata,
                              ndraws = NULL, draw_ids = NULL) {
  side <- hit$side
  if (is.null(newdata)) newdata <- object$data
  side_form <- mvgam_side_formula(object, side)
  suffix <- mvgam_side_suffix(side)
  # Backfill any missing response column so brms::standata's
  # validate_newdata accepts the grid. Family-aware dummy mirrors
  # brms::check_response = FALSE.
  resp <- all.vars(side_form$formula[[2L]])[1L]
  if (!is.null(resp) && !(resp %in% names(newdata))) {
    fam <- object$family
    if (!inherits(fam, "brmsfamily")) {
      fam <- brms::brmsfamily(fam$family, link = fam$link)
    }
    newdata[[resp]] <- get_safe_dummy_value(fam)
  }
  # brms::standata routes through the brmsfit-shaped side model's
  # stored basis (computed at fit time), so PredictMat handles
  # any newdata grid — sparse or dense — without re-running
  # smoothCon. This is exactly what brms's posterior_smooths does.
  #
  # Pass `check_response = FALSE` and `internal = TRUE` so brms
  # skips response + aterm validation on `newdata` — this matches
  # what `brms:::posterior_smooths.btl` does and prevents
  # family-specific aterm columns (e.g. `| trials(N)` for
  # binomial fits) from raising errors when the caller's grid
  # doesn't carry those columns.
  side_model <- if (identical(side, "trend")) {
    object$trend_model
  } else {
    object$obs_model
  }
  sd_new <- brms::standata(
    side_model, newdata = newdata,
    check_response = FALSE, internal = TRUE
  )
  # Focal smooth's Xs columns + the canonical bs_ aliases for
  # those columns (stored at fit time on `object$standata$Xs`).
  Xs_key <- paste0("Xs", suffix)
  Xs_full <- sd_new[[Xs_key]]
  smcols <- attr(Xs_full, "smcols")
  Xs_focal <- if (!is.null(Xs_full) && length(smcols) > 0L) {
    cols <- unlist(smcols[hit$rows])
    if (length(cols) > 0L) {
      out <- Xs_full[, cols, drop = FALSE]
      colnames(out) <- paste0(
        "bs_", colnames(Xs_full)[cols], suffix
      )
      out
    } else {
      NULL
    }
  } else {
    NULL
  }
  zs_blocks <- list()
  for (r in hit$rows) {
    keys <- grep(
      sprintf("^Zs_%d_\\d+%s$", r, suffix),
      names(sd_new), value = TRUE
    )
    for (k in keys) {
      zs_blocks[[length(zs_blocks) + 1L]] <- list(
        Z = sd_new[[k]],
        s_pattern = sub("^Zs_", "s_", k)
      )
    }
  }
  drws <- extract_mvgam_draws(object)
  drws_mat <- posterior::as_draws_matrix(drws)
  drws_mat <- subset_draws_for_smooth(drws_mat, ndraws, draw_ids)
  eta <- matrix(0, nrow = nrow(drws_mat),
                 ncol = nrow(newdata))
  if (!is.null(Xs_focal) && ncol(Xs_focal) > 0L) {
    bs_aliases <- colnames(Xs_focal)
    missing_bs <- setdiff(bs_aliases, colnames(drws_mat))
    if (length(missing_bs) > 0L) {
      stop(insight::format_error(c(
        paste0(
          "Internal: expected smooth fixed-effect ",
          "coefficients not found in the cached draws."
        ),
        x = paste0(
          "Missing: ",
          paste0("'", missing_bs, "'", collapse = ", ")
        )
      )))
    }
    bs_draws <- drws_mat[, bs_aliases, drop = FALSE]
    eta <- eta + bs_draws %*% t(Xs_focal)
  }
  for (blk in zs_blocks) {
    pattern <- paste0("^", gsub("([\\[\\]])", "\\\\\\1",
                                  blk$s_pattern), "\\[")
    s_names <- grep(pattern, colnames(drws_mat),
                     value = TRUE)
    if (length(s_names) == 0L) next
    s_draws <- drws_mat[, s_names, drop = FALSE]
    eta <- eta + s_draws %*% t(blk$Z)
  }
  eta
}


# Apply brms-style ndraws / draw_ids subsetting to a draws matrix.
#'@noRd
subset_draws_for_smooth <- function(drws_mat, ndraws, draw_ids) {
  n_avail <- nrow(drws_mat)
  if (!is.null(draw_ids)) {
    if (max(draw_ids) > n_avail) {
      stop(insight::format_error(c(
        "'draw_ids' references draws beyond the available range.",
        x = paste0(
          "Max requested: ", max(draw_ids),
          "; available: ", n_avail, "."
        )
      )))
    }
    return(drws_mat[draw_ids, , drop = FALSE])
  }
  if (!is.null(ndraws)) {
    if (ndraws > n_avail) {
      stop(insight::format_error(c(
        "'ndraws' exceeds available posterior draws.",
        x = paste0(
          "Requested: ", ndraws,
          "; available: ", n_avail, "."
        )
      )))
    }
    return(drws_mat[sample(n_avail, ndraws), , drop = FALSE])
  }
  drws_mat
}


# Build the prediction grid for one smooth term. Mirrors brms's
# conditional_smooths grid logic: 1D smooths sweep the focal
# covariate; 2D smooths get a surface grid by default, or a
# faceted-line layout when `surface = FALSE` (with `facets`
# controlling the facet count); >2D smooths recursively move
# non-focal covariates into the by-variable set so the facet
# strip degrades to a discrete grouping.
#'@noRd
build_smooth_grid <- function(x, hit, surface, facets, resolution,
                                int_conditions, too_far) {
  mf <- x$data
  side_form_bf <- mvgam_side_formula(x, hit$side)
  side_form <- side_form_bf$formula
  spec <- mvgam_smooth_label_spec(side_form_bf)$spec[[hit$term_idx]]
  covars <- spec$term
  byvars <- if (!is.na(hit$by_var) && !identical(hit$by_var, "NA")) {
    hit$by_var
  } else {
    character(0L)
  }
  # Promote excess covariates beyond the first two into facet
  # variables to keep the plot dispatch sensible.
  if (length(covars) > 2L) {
    byvars <- c(covars[-(1:2)], byvars)
    covars <- covars[1:2]
  }
  is_numeric <- vapply(covars, function(cv) {
    is.numeric(mf[[cv]])
  }, logical(1L))
  values <- stats::setNames(vector("list", length(covars)), covars)
  for (i in seq_along(covars)) {
    cv <- covars[i]
    if (!is.null(int_conditions) && cv %in% names(int_conditions)) {
      ic <- int_conditions[[cv]]
      if (is.function(ic)) ic <- ic(mf[[cv]])
      values[[cv]] <- ic
    } else if (is_numeric[i]) {
      if (i == 2L && !isTRUE(surface)) {
        m <- mean(mf[[cv]], na.rm = TRUE)
        s <- stats::sd(mf[[cv]], na.rm = TRUE)
        if (facets <= 1L) {
          values[[cv]] <- m
        } else {
          q <- seq(-1, 1, length.out = facets)
          values[[cv]] <- m + q * s
        }
      } else {
        values[[cv]] <- seq(
          min(mf[[cv]], na.rm = TRUE),
          max(mf[[cv]], na.rm = TRUE),
          length.out = resolution
        )
      }
    } else {
      values[[cv]] <- levels(factor(mf[[cv]]))
    }
  }
  for (cv in byvars) {
    if (!is.null(int_conditions) && cv %in% names(int_conditions)) {
      ic <- int_conditions[[cv]]
      if (is.function(ic)) ic <- ic(mf[[cv]])
      values[[cv]] <- ic
    } else if (is.numeric(mf[[cv]])) {
      m <- mean(mf[[cv]], na.rm = TRUE)
      s <- stats::sd(mf[[cv]], na.rm = TRUE)
      values[[cv]] <- m + seq(-1, 1, length.out = facets) * s
    } else {
      values[[cv]] <- levels(factor(mf[[cv]]))
    }
  }
  grid <- expand.grid(values, stringsAsFactors = FALSE)
  # Drop grid points too far from the training data on a 2D
  # surface (brms-parity).
  if (length(covars) == 2L && isTRUE(surface) && too_far > 0) {
    ex <- mgcv::exclude.too.far(
      g1 = grid[[covars[1L]]], g2 = grid[[covars[2L]]],
      d1 = mf[[covars[1L]]], d2 = mf[[covars[2L]]],
      dist = too_far
    )
    grid <- grid[!ex, , drop = FALSE]
  }
  # Backfill non-focal covariates and the response with reasonable
  # defaults so brms::standata can build the basis matrices.
  newdata <- backfill_smooth_grid(grid, x, side_form, covars, byvars)
  cond_data <- grid
  cond_data$effect1__ <- cond_data[[covars[1L]]]
  if (length(covars) == 2L) {
    if (isTRUE(surface)) {
      cond_data$effect2__ <- cond_data[[covars[2L]]]
    } else {
      lvls <- sort(unique(cond_data[[covars[2L]]]), decreasing = TRUE)
      cond_data$effect2__ <- factor(
        round(cond_data[[covars[2L]]], 3L), levels = round(lvls, 3L)
      )
    }
  }
  if (length(byvars) > 0L) {
    cond_data$cond__ <- factor(do.call(
      paste, c(cond_data[byvars], list(sep = " : "))
    ))
  } else {
    cond_data$cond__ <- factor(1L)
  }
  list(
    newdata = newdata, cond_data = cond_data,
    effects = covars, surface = isTRUE(surface) &&
      length(covars) == 2L
  )
}


# Backfill the prediction-grid `data.frame` so brms::standata can
# build basis matrices. Non-focal covariates get their training
# median (numeric) or first level (factor); the response is set
# to a dummy value because the basis matrices are response-free.
#'@noRd
backfill_smooth_grid <- function(grid, x, side_form, covars, byvars) {
  mf <- x$data
  resp <- all.vars(side_form[[2L]])[1L]
  # Strip the response from the backfill set: the dummy gets a
  # family-aware value via `mvgam_smooth_eta`. Setting it to the
  # training median here can violate family bounds (e.g.
  # numeric median fails the Poisson integer check).
  non_focal <- setdiff(all.vars(side_form), c(covars, byvars, resp))
  for (cv in non_focal) {
    if (cv %in% names(mf)) {
      col <- mf[[cv]]
      grid[[cv]] <- if (is.numeric(col)) {
        stats::median(col, na.rm = TRUE)
      } else if (is.factor(col)) {
        factor(levels(col)[1L], levels = levels(col))
      } else {
        col[1L]
      }
    }
  }
  if (!is.null(resp) && resp %in% names(grid)) {
    grid[[resp]] <- NULL
  }
  grid
}


# Build the spaghetti-overlay data.frame brms's plot dispatch
# consumes: one row per (draw, grid_point) with columns
# (effect1__, estimate__, sample__).
#'@noRd
build_spaghetti_data <- function(eta, cond_data, effects) {
  n_draws <- nrow(eta)
  n_grid <- ncol(eta)
  out <- data.frame(
    effect1__ = rep(cond_data[[effects[1L]]], times = n_draws),
    estimate__ = as.numeric(t(eta)),
    sample__ = factor(rep(seq_len(n_draws), each = n_grid))
  )
  out
}


# Extract the training-data points the plot method overlays.
# Returns the covariate values from the training data for the
# focal smooth, restricted to the by-factor level (when present)
# so the overlay tracks the corresponding facet.
#'@noRd
mvgam_smooth_points <- function(x, hit, grid_spec) {
  mf <- x$data
  effects <- grid_spec$effects
  if (any(!effects %in% names(mf))) {
    return(data.frame())
  }
  out <- data.frame(mf[, effects, drop = FALSE])
  colnames(out) <- paste0("effect", seq_along(effects), "__")
  out
}
