# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
trend_arma_recursC <- function(ar_lags, ma_lags, drift, A, B, innovations, linpreds, last_trends, h) {
    .Call(`_mvgam_trend_arma_recursC`, ar_lags, ma_lags, drift, A, B, innovations, linpreds, last_trends, h)
}

#' @noRd
car1_recursC <- function(phi, sigma, time_dis, innovations, last_trend, h) {
    .Call(`_mvgam_car1_recursC`, phi, sigma, time_dis, innovations, last_trend, h)
}

