# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ar3_recursC <- function(drift, ar1, ar2, ar3, linpreds, errors, last_trends, h) {
    .Call('_mvgam_ar3_recursC', PACKAGE = 'mvgam', drift, ar1, ar2, ar3, linpreds, errors, last_trends, h)
}

var1_recursC <- function(A, linpreds, errors, last_trends, h) {
    .Call('_mvgam_var1_recursC', PACKAGE = 'mvgam', A, linpreds, errors, last_trends, h)
}

