# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: memcheck

jobs:
  memcheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: false

    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: apt install dependency
        run: |
          sudo apt-get -y install valgrind

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: NA
          extra-packages: |
              devtools
              testthat

      - name: Memory check
        run: |
          R -d valgrind -f memcheck.R

      - name: Configure GH
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"


      - name: Install Air latest
        shell: bash
        run: |
          curl -LsSf https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sh

      - name: Air version
        shell: bash
        run: |
          echo ""
          echo "Formatting R code with $(air --version)"
          echo ""

      - name: Format R code using Air
        shell: bash
        run: air format .

      - name: Commit any Air formatting changes
        shell: bash
        run: |
          if find . -type f \( -name '*.r' -o -name '*.R' \) -exec git add -u {} +; then
            echo "Staged modified R files"
            git commit -a -m '`air format` (GitHub Actions)'
            git push
          else
            echo "No changes found in any R files"
          fi
